"""v0_2_otp_columns_added

Revision ID: b267b7f464bd
Revises: e494a7364d0f
Create Date: 2024-03-08 15:01:36.467519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b267b7f464bd'
down_revision: Union[str, None] = 'e494a7364d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otps', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('otps', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otps', 'updated_at')
    op.drop_column('otps', 'is_verified')
    # ### end Alembic commands ###
